In [49]:
from os import listdir
from os.path import isfile, isdir, join
from pathlib import Path

import numpy as np

mypath = Path('/home/student/work/3d_Generative/model/dataset/dataset')

classes = [d for d in listdir(mypath) if isdir(mypath / d) and d[0] != '.']
splits = {class_: split for class_, split in  zip(classes, [listdir(mypath / d) for d in classes])}
objects = {class_: {split_: objects for split_, objects in zip(split, [[val for val in listdir(mypath / class_ / split_name) if val[0] != '.' ] for split_name in split])} for class_, split in zip(splits.keys(), splits.values())}
objects

{'bathtub': {'train': ['bathtub_0025',
   'bathtub_0076',
   'bathtub_0031',
   'bathtub_0035',
   'bathtub_0094',
   'bathtub_0096'],
  'test': ['bathtub_0109',
   'bathtub_0113',
   'bathtub_0107',
   'bathtub_0110',
   'bathtub_0112',
   'bathtub_0108']},
 'sofa': {'train': ['sofa_0652',
   'sofa_0310',
   'sofa_0491',
   'sofa_0179',
   'sofa_0242',
   'sofa_0546',
   'sofa_0197',
   'sofa_0170',
   'sofa_0382',
   'sofa_0525']},
 'chair': {'train': ['chair_0320',
   'chair_0615',
   'chair_0083',
   'chair_0820',
   'chair_0336',
   'chair_0047',
   'chair_0544'],
  'test': ['chair_0936', 'chair_0904', 'chair_0899']},
 'toilet': {'train': ['toilet_0238', 'toilet_0192', 'toilet_0163'],
  'test': ['toilet_0423', 'toilet_0429']},
 'dresser': {'train': ['dresser_0006',
   'dresser_0068',
   'dresser_0129',
   'dresser_0097',
   'dresser_0071',
   'dresser_0065'],
  'test': ['dresser_0257', 'dresser_0211', 'dresser_0263', 'dresser_0252']},
 'desk': {'train': ['desk_0039',
   'desk_0080',
   'desk_0165',
   'desk_0034',
   'desk_0038',
   'desk_0195',
   'desk_0023',
   'desk_0137',
   'desk_0194'],
  'test': ['desk_0277']},
 'table': {'train': ['table_0010',
   'table_0345',
   'table_0318',
   'table_0098',
   'table_0141',
   'table_0287'],
  'test': ['table_0449', 'table_0481']},
 'monitor': {'train': ['monitor_0111',
   'monitor_0033',
   'monitor_0296',
   'monitor_0430',
   'monitor_0291',
   'monitor_0307'],
  'test': ['monitor_0495', 'monitor_0504', 'monitor_0535', 'monitor_0553']},
 'night': {'train': ['night_stand_0064',
   'night_stand_0036',
   'night_stand_0119',
   'night_stand_0052',
   'night_stand_0062',
   'night_stand_0027'],
  'test': ['night_stand_0254',
   'night_stand_0268',
   'night_stand_0236',
   'night_stand_0208']},
 'bed': {'train': ['bed_0455',
   'bed_0510',
   'bed_0091',
   'bed_0471',
   'bed_0354',
   'bed_0256',
   'bed_0448',
   'bed_0032',
   'bed_0389',
   'bed_0242']}}

In [88]:
import pandas as pd

def get_colors(path_to_filedir):
    return [i for i in listdir(path_to_filedir) if i.split('_')[-1] == 'rgb.pt'][0]

def get_densities(path_to_filedir):
    return [i for i in listdir(path_to_filedir) if i.split('_')[-1] == 'd.pt'][0]

dataframe_dict = {'object_id': [], 'class': [], 'split': [], 'color_path': [], 'density_path': []}
for class_ in objects.keys():
    for split in objects[class_].keys():
        for object_ in objects[class_][split]:
            dataframe_dict['object_id'].append(object_)
            dataframe_dict['class'].append(class_)
            dataframe_dict['split'].append(split)
            dataframe_dict['color_path'].append(mypath / class_ / split / object_ / get_colors(mypath / class_ / split / object_))
            dataframe_dict['density_path'].append(mypath / class_ / split / object_ / get_densities(mypath / class_ / split / object_))

data_real = pd.DataFrame(dataframe_dict)
data_real

,object_id,class,split,color_path,density_path
0,bathtub_0025,bathtub,train,/home/student/work/3d_Generative/model/dataset...,/home/student/work/3d_Generative/model/dataset...
1,bathtub_0076,bathtub,train,/home/student/work/3d_Generative/model/dataset...,/home/student/work/3d_Generative/model/dataset...
2,bathtub_0031,bathtub,train,/home/student/work/3d_Generative/model/dataset...,/home/student/work/3d_Generative/model/dataset...
3,bathtub_0035,bathtub,train,/home/student/work/3d_Generative/model/dataset...,/home/student/work/3d_Generative/model/dataset...
4,bathtub_0094,bathtub,train,/home/student/work/3d_Generative/model/dataset...,/home/student/work/3d_Generative/model/dataset...
...,...,...,...,...,...
90,bed_0256,bed,train,/home/student/work/3d_Generative/model/dataset...,/home/student/work/3d_Generative/model/dataset...
91,bed_0448,bed,train,/home/student/work/3d_Generative/model/dataset...,/home/student/work/3d_Generative/model/dataset...
92,bed_0032,bed,train,/home/student/work/3d_Generative/model/dataset...,/home/student/work/3d_Generative/model/dataset...
93,bed_0389,bed,train,/home/student/work/3d_Generative/model/dataset...,/home/student/work/3d_Generative/model/dataset...
94,bed_0242,bed,train,/home/student/work/3d_Generative/model/dataset...,/home/student/work/3d_Generative/model/dataset...

In [114]:
isfile('/home/student/work/3d_Generative/model/dataset/dataset/table/train/table_0141/table_0141_d.pt')

True

In [89]:
data_done = pd.read_csv('modelnet_converted.csv')
data_done

,object_id,class,split,color_path,density_path
0,bathtub_0107,bathtub,test,/home/student/work/3d_Generative/model/dataset...,/home/student/work/3d_Generative/model/dataset...
1,bathtub_0108,bathtub,test,/home/student/work/3d_Generative/model/dataset...,/home/student/work/3d_Generative/model/dataset...
2,bathtub_0109,bathtub,test,/home/student/work/3d_Generative/model/dataset...,/home/student/work/3d_Generative/model/dataset...
3,bathtub_0110,bathtub,test,/home/student/work/3d_Generative/model/dataset...,/home/student/work/3d_Generative/model/dataset...
4,bathtub_0112,bathtub,test,/home/student/work/3d_Generative/model/dataset...,/home/student/work/3d_Generative/model/dataset...
...,...,...,...,...,...
82,sofa_0652,sofa,train,/home/student/work/3d_Generative/model/dataset...,/home/student/work/3d_Generative/model/dataset...
83,sofa_0491,sofa,train,/home/student/work/3d_Generative/model/dataset...,/home/student/work/3d_Generative/model/dataset...
84,table_0098,table,train,/home/student/work/3d_Generative/model/dataset...,/home/student/work/3d_Generative/model/dataset...
85,table_0449,table,test,/home/student/work/3d_Generative/model/dataset...,/home/student/work/3d_Generative/model/dataset...
86,table_0141,table,train,/home/student/work/3d_Generative/model/dataset...,/home/student/work/3d_Generative/model/dataset...

In [90]:
data_real = pd.concat([data_real, data_done])
data_real = data_real.drop_duplicates(subset=['object_id'], keep=False)
data_real

,object_id,class,split,color_path,density_path
32,toilet_0238,toilet,train,/home/student/work/3d_Generative/model/dataset...,/home/student/work/3d_Generative/model/dataset...
33,toilet_0192,toilet,train,/home/student/work/3d_Generative/model/dataset...,/home/student/work/3d_Generative/model/dataset...
34,toilet_0163,toilet,train,/home/student/work/3d_Generative/model/dataset...,/home/student/work/3d_Generative/model/dataset...
35,toilet_0423,toilet,test,/home/student/work/3d_Generative/model/dataset...,/home/student/work/3d_Generative/model/dataset...
36,toilet_0429,toilet,test,/home/student/work/3d_Generative/model/dataset...,/home/student/work/3d_Generative/model/dataset...
57,table_0010,table,train,/home/student/work/3d_Generative/model/dataset...,/home/student/work/3d_Generative/model/dataset...
62,table_0287,table,train,/home/student/work/3d_Generative/model/dataset...,/home/student/work/3d_Generative/model/dataset...
64,table_0481,table,test,/home/student/work/3d_Generative/model/dataset...,/home/student/work/3d_Generative/model/dataset...

In [111]:
for row in data_real.iterrows():
    print(','.join([str(i) for i in row[1].to_list()]))

toilet_0238,toilet,train,/home/student/work/3d_Generative/model/dataset/dataset/toilet/train/toilet_0238/toilet_0238_rgb.pt,/home/student/work/3d_Generative/model/dataset/dataset/toilet/train/toilet_0238/toilet_0238_d.pt
toilet_0192,toilet,train,/home/student/work/3d_Generative/model/dataset/dataset/toilet/train/toilet_0192/toilet_0192_rgb.pt,/home/student/work/3d_Generative/model/dataset/dataset/toilet/train/toilet_0192/toilet_0192_d.pt
toilet_0163,toilet,train,/home/student/work/3d_Generative/model/dataset/dataset/toilet/train/toilet_0163/toilet_0163_rgb.pt,/home/student/work/3d_Generative/model/dataset/dataset/toilet/train/toilet_0163/toilet_0163_d.pt
toilet_0423,toilet,test,/home/student/work/3d_Generative/model/dataset/dataset/toilet/test/toilet_0423/toilet_0423_rgb.pt,/home/student/work/3d_Generative/model/dataset/dataset/toilet/test/toilet_0423/toilet_0423_d.pt
toilet_0429,toilet,test,/home/student/work/3d_Generative/model/dataset/dataset/toilet/test/toilet_0429/toilet_0429_rgb.pt,/home/student/work/3d_Generative/model/dataset/dataset/toilet/test/toilet_0429/toilet_0429_d.pt
table_0010,table,train,/home/student/work/3d_Generative/model/dataset/dataset/table/train/table_0010/table_0010_rgb.pt,/home/student/work/3d_Generative/model/dataset/dataset/table/train/table_0010/table_0010_d.pt
table_0287,table,train,/home/student/work/3d_Generative/model/dataset/dataset/table/train/table_0287/table_0287_rgb.pt,/home/student/work/3d_Generative/model/dataset/dataset/table/train/table_0287/table_0287_d.pt
table_0481,table,test,/home/student/work/3d_Generative/model/dataset/dataset/table/test/table_0481/table_0481_rgb.pt,/home/student/work/3d_Generative/model/dataset/dataset/table/test/table_0481/table_0481_d.pt

In [113]:
with open('modelnet_converted.csv', 'a') as file:
    for row in data_real.iterrows():
        file.write(f"{','.join([str(i) for i in row[1].to_list()])}\n")